In [39]:

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import joblib

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, f1_score

RANDOM_STATE = 42
PLOT_BLUE, PLOT_ORANGE = "#1779A8", "#C96A00"  # course plot colours

pd.set_option('display.max_columns', 50) # tells pandas to display up to 50 columns when printing a DataFrame
pd.set_option('display.max_rows', 50)    # tells pandas to display up to 50 rows when printing a DataFrame

In [40]:
Directory = '/Users/josemenezes/Faculdade/Projetos/Projeto ML/Projeto-Machine-Learning/project/data/'

train_data = pd.read_csv(Directory + 'train.csv', index_col='customer_id')
teste_data = pd.read_csv(Directory + 'test.csv',index_col='customer_id')
clients = pd.read_csv(Directory + 'clientes.csv', index_col='customer_id')

print("train data:", train_data.shape, "| test data:", teste_data.shape, "| clients data:", clients.shape)

train data: (6534, 38) | test data: (986, 37) | clients data: (1143, 12)

In [41]:
merged_data = train_data.merge(clients, on='customer_id', how='inner')

In [42]:
merged_data.shape

(6534, 50)

In [43]:
merged_data.head()

,Total a Pagar,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,repeat_purchase_90d,days_since_previous_purchase,customer_tenure_days,prior_purchase_count,prior_total_spend,prior_mean_purchase_value,prior_std_purchase_value,prior_min_purchase_value,prior_max_purchase_value,prior_mean_gap_days,prior_std_gap_days,purchase_count_30d,spend_30d,purchase_count_90d,spend_90d,purchase_count_180d,spend_180d,purchase_count_365d,spend_365d,payment_type,salesperson,commercial_zone,transport_method,warehouse,document_series,purchase_date,ID,random_noise,country_or_region,commercial_region,island,municipality,city,postal_area,postal_code,street,address,customer_type,company_name,customer_since_year
customer_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
660784,558.11,510.90,453.75,104.36,0.0,0.0,57.15,153.099911,4.0,1.0,1,79.0,126.0,2.0,858.30,429.150000,112.656252,349.49,508.81,47.000000,NaN,0.0,0.00,1.0,349.49,2.0,858.30,2.0,858.30,Maybe Tomorrow Payment 10,VLOOKUP Master 9,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 2,2024-10-29,10000000,-0.660448,Country CT10: Land of The Final Version,Region RG25: We Will See Later,NaN,Municipality MU89: Council of Last Minute Edits,City CY286: Cached Result Falls,Postal area PA228: Hidden Sheet Sector,Postal code PC444: #REF! Delivery Route,Street ST303: Absolute Reference Terrace,Address AD761: Cell Without a Home,NaN,Excel Is Not A Database Ltd 1013,2024
189146,978.80,830.02,795.77,183.03,0.0,0.0,34.25,472.943134,32.0,1.0,1,244.0,616.0,5.0,6722.83,1344.566000,1683.795178,84.38,4222.15,93.000000,117.657696,0.0,0.00,0.0,0.00,0.0,0.00,4.0,2500.68,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 36,Final Excel Warehouse 1,Ctrl Z Series 1,2017-07-08,10000001,0.924510,Country CT10: Land of The Final Version,Region RG17: We Will See Later,Island IS8: The Pivot Archipelago,Municipality MU11: Council of Last Minute Edits,City CY147: VLOOKUP Bay,Postal area PA260: Hidden Sheet Sector,Postal code PC636: #REF! Delivery Route,NaN,Address AD382: Cell Without a Home,NaN,Excel Is Not A Database Ltd 35,2015
103940,10.33,12.00,8.40,1.93,0.0,0.0,3.60,6.097485,1.0,1.0,1,9.0,610.0,90.0,17590.08,195.445333,190.389932,4.54,1002.15,6.752809,6.384073,2.0,111.27,9.0,1928.55,28.0,5290.25,49.0,7899.80,Maybe Tomorrow Payment 9,VLOOKUP Master 1,Decorative Dashboard Zone 4,NaN,Final Excel Warehouse 1,Ctrl Z Series 3,2019-03-19,10000002,-0.258730,Country CT10: Land of The Final Version,Region RG23: We Will See Later,NaN,Municipality MU70: Council of Last Minute Edits,City CY265: Where-less Query Falls,Postal area PA84: Hidden Sheet Sector,Postal code PC200: #REF! Delivery Route,NaN,Address AD723: Cell Without a Home,NaN,Excel Is Not A Database Ltd 826,2017
512927,856.83,696.61,696.61,160.22,0.0,0.0,0.00,408.167275,9.0,1.0,0,97.0,97.0,1.0,270.33,270.330000,NaN,270.33,270.33,NaN,NaN,0.0,0.00,0.0,0.00,1.0,270.33,1.0,270.33,Maybe Tomorrow Payment 7,VLOOKUP Master 4,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 71,Final Excel Warehouse 1,Ctrl Z Series 3,2018-11-10,10000003,1.448402,Country CT10: Land of The Final Version,Region RG17: We Will See Later,Island IS7: The Pivot Archipelago,Municipality MU12: Council of Last Minute Edits,NaN,Postal area PA253: Hidden Sheet Sector,Postal code PC558: #REF! Delivery Route,Street ST144: Last Save Court,Address AD399: Cell Without a Home,NaN,Excel Is Not A Database Ltd 530,2018
122356,1616.10,1488.85,1313.90,302.20,0.0,0.0,174.95,485.401864,33.0,1.0,1,85.0,1575.0,25.0,12803.02,512.120800,406.696963,22.58,1736.74,62.083333,66.246520,0.0,0.00,2.0,184.13,4.0,2062.50,4.0,2062.50,Maybe Tomorrow Payment 12,NaN,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 2,2021-11-30,10000004,-1.058890,Country CT10: Land of The Final Version,Region RG31: We Will See Later,NaN,Municipality MU142: Council of Last Minute Edits,City CY359: Spill Error Ridge,Postal area PA136: Hidden Sheet Sector,Postal code PC300: #REF! Delivery Route,Street ST395: AutoFill Path,Address AD928: Cell Without a Home,NaN,Excel Is Not A Database Ltd 220,2017

In [44]:
merged_data=merged_data.drop('customer_type', axis=1)

In [45]:
merged_data.info()

<class 'pandas.DataFrame'>
Index: 6534 entries, 660784 to 438652
Data columns (total 49 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Total a Pagar                   6469 non-null   float64
 1   Total Bruto                     6469 non-null   float64
 2   Total Liquido                   6469 non-null   float64
 3   Total Imp_                      6469 non-null   float64
 4   Total Portes                    6469 non-null   float64
 5   Total Desc_ Global              6469 non-null   float64
 6   Total Desc_ Linha               6469 non-null   float64
 7   Custo                           6469 non-null   float64
 8   N_ Detalhes                     6469 non-null   float64
 9   invoice_count_current_purchase  6469 non-null   float64
 10  repeat_purchase_90d             6534 non-null   int64
 11  days_since_previous_purchase    5673 non-null   float64
 12  customer_tenure_days            6469 non-null   float64
 13  prior_purchase_count            6469 non-null   float64
 14  prior_total_spend               6469 non-null   float64
 15  prior_mean_purchase_value       5672 non-null   float64
 16  prior_std_purchase_value        5421 non-null   float64
 17  prior_min_purchase_value        5866 non-null   float64
 18  prior_max_purchase_value        5866 non-null   float64
 19  prior_mean_gap_days             5226 non-null   float64
 20  prior_std_gap_days              5056 non-null   float64
 21  purchase_count_30d              6469 non-null   float64
 22  spend_30d                       6469 non-null   float64
 23  purchase_count_90d              6469 non-null   float64
 24  spend_90d                       6469 non-null   float64
 25  purchase_count_180d             6469 non-null   float64
 26  spend_180d                      6469 non-null   float64
 27  purchase_count_365d             6469 non-null   float64
 28  spend_365d                      6274 non-null   float64
 29  payment_type                    6274 non-null   str
 30  salesperson                     6275 non-null   str
 31  commercial_zone                 6469 non-null   str
 32  transport_method                6273 non-null   str
 33  warehouse                       6274 non-null   str
 34  document_series                 6469 non-null   str
 35  purchase_date                   6469 non-null   str
 36  ID                              6534 non-null   int64
 37  random_noise                    6469 non-null   float64
 38  country_or_region               6534 non-null   str
 39  commercial_region               6499 non-null   str
 40  island                          4323 non-null   str
 41  municipality                    6317 non-null   str
 42  city                            4384 non-null   str
 43  postal_area                     6256 non-null   str
 44  postal_code                     6309 non-null   str
 45  street                          2700 non-null   str
 46  address                         6534 non-null   str
 47  company_name                    6534 non-null   str
 48  customer_since_year             6534 non-null   int64
dtypes: float64(29), int64(3), str(17)
memory usage: 2.5 MB

In [46]:
for col in merged_data.columns: # I used this for loop to remove all str columns to test a first model
    if merged_data[col].dtype == "str":
        merged_data = merged_data.drop(columns=col)

In [47]:
merged_data.info()

<class 'pandas.DataFrame'>
Index: 6534 entries, 660784 to 438652
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Total a Pagar                   6469 non-null   float64
 1   Total Bruto                     6469 non-null   float64
 2   Total Liquido                   6469 non-null   float64
 3   Total Imp_                      6469 non-null   float64
 4   Total Portes                    6469 non-null   float64
 5   Total Desc_ Global              6469 non-null   float64
 6   Total Desc_ Linha               6469 non-null   float64
 7   Custo                           6469 non-null   float64
 8   N_ Detalhes                     6469 non-null   float64
 9   invoice_count_current_purchase  6469 non-null   float64
 10  repeat_purchase_90d             6534 non-null   int64
 11  days_since_previous_purchase    5673 non-null   float64
 12  customer_tenure_days            6469 non-null   float64
 13  prior_purchase_count            6469 non-null   float64
 14  prior_total_spend               6469 non-null   float64
 15  prior_mean_purchase_value       5672 non-null   float64
 16  prior_std_purchase_value        5421 non-null   float64
 17  prior_min_purchase_value        5866 non-null   float64
 18  prior_max_purchase_value        5866 non-null   float64
 19  prior_mean_gap_days             5226 non-null   float64
 20  prior_std_gap_days              5056 non-null   float64
 21  purchase_count_30d              6469 non-null   float64
 22  spend_30d                       6469 non-null   float64
 23  purchase_count_90d              6469 non-null   float64
 24  spend_90d                       6469 non-null   float64
 25  purchase_count_180d             6469 non-null   float64
 26  spend_180d                      6469 non-null   float64
 27  purchase_count_365d             6469 non-null   float64
 28  spend_365d                      6274 non-null   float64
 29  ID                              6534 non-null   int64
 30  random_noise                    6469 non-null   float64
 31  customer_since_year             6534 non-null   int64
dtypes: float64(29), int64(3)
memory usage: 1.6 MB

In [48]:
merged_data.head()

,Total a Pagar,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,repeat_purchase_90d,days_since_previous_purchase,customer_tenure_days,prior_purchase_count,prior_total_spend,prior_mean_purchase_value,prior_std_purchase_value,prior_min_purchase_value,prior_max_purchase_value,prior_mean_gap_days,prior_std_gap_days,purchase_count_30d,spend_30d,purchase_count_90d,spend_90d,purchase_count_180d,spend_180d,purchase_count_365d,spend_365d,ID,random_noise,customer_since_year
customer_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
660784,558.11,510.90,453.75,104.36,0.0,0.0,57.15,153.099911,4.0,1.0,1,79.0,126.0,2.0,858.30,429.150000,112.656252,349.49,508.81,47.000000,NaN,0.0,0.00,1.0,349.49,2.0,858.30,2.0,858.30,10000000,-0.660448,2024
189146,978.80,830.02,795.77,183.03,0.0,0.0,34.25,472.943134,32.0,1.0,1,244.0,616.0,5.0,6722.83,1344.566000,1683.795178,84.38,4222.15,93.000000,117.657696,0.0,0.00,0.0,0.00,0.0,0.00,4.0,2500.68,10000001,0.924510,2015
103940,10.33,12.00,8.40,1.93,0.0,0.0,3.60,6.097485,1.0,1.0,1,9.0,610.0,90.0,17590.08,195.445333,190.389932,4.54,1002.15,6.752809,6.384073,2.0,111.27,9.0,1928.55,28.0,5290.25,49.0,7899.80,10000002,-0.258730,2017
512927,856.83,696.61,696.61,160.22,0.0,0.0,0.00,408.167275,9.0,1.0,0,97.0,97.0,1.0,270.33,270.330000,NaN,270.33,270.33,NaN,NaN,0.0,0.00,0.0,0.00,1.0,270.33,1.0,270.33,10000003,1.448402,2018
122356,1616.10,1488.85,1313.90,302.20,0.0,0.0,174.95,485.401864,33.0,1.0,1,85.0,1575.0,25.0,12803.02,512.120800,406.696963,22.58,1736.74,62.083333,66.246520,0.0,0.00,2.0,184.13,4.0,2062.50,4.0,2062.50,10000004,-1.058890,2017

In [49]:
merged_data.describe()

,Total a Pagar,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,repeat_purchase_90d,days_since_previous_purchase,customer_tenure_days,prior_purchase_count,prior_total_spend,prior_mean_purchase_value,prior_std_purchase_value,prior_min_purchase_value,prior_max_purchase_value,prior_mean_gap_days,prior_std_gap_days,purchase_count_30d,spend_30d,purchase_count_90d,spend_90d,purchase_count_180d,spend_180d,purchase_count_365d,spend_365d,ID,random_noise,customer_since_year
count,6469.000000,6469.000000,6469.000000,6469.000000,6469.000000,6469.000000,6469.000000,6469.000000,6469.000000,6469.000000,6534.000000,5673.000000,6469.000000,6469.000000,6469.000000,5.672000e+03,5421.000000,5866.000000,5866.000000,5226.000000,5056.000000,6469.000000,6469.000000,6469.000000,6469.000000,6469.000000,6469.000000,6469.000000,6.274000e+03,6.534000e+03,6469.000000,6534.000000
mean,925.556262,886.152705,773.336384,152.219878,1.151427,0.349907,112.466414,328.165040,21.524501,1.066007,0.559229,101.530231,1111.383676,23.457876,18908.348876,2.821825e+06,737.469683,185.462003,2946.378367,95.876660,74.135443,0.600557,457.141009,1.631937,1253.527977,3.374556,2650.599796,6.561601,2.396535e+06,1.000383e+07,-0.022140,2016.434956
std,1334.997733,1327.641086,1136.355723,225.262375,5.844091,5.116564,289.986307,519.507218,27.713419,0.310807,0.496518,165.704875,923.190795,38.344845,31130.865216,5.304157e+07,666.261939,408.398582,5901.547558,122.589306,101.819540,1.214975,1191.231401,2.977981,2347.842270,5.460510,4020.267397,10.325535,4.884113e+07,2.218817e+03,1.001054,2.074381
min,0.930000,0.830000,0.760000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,-4.000000,0.000000,0.000000,0.000000,-2.478658e+03,0.000000,0.930000,3.310000,-4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.591152e+05,1.000000e+07,-3.529210,2015.000000
25%,188.920000,175.740000,154.380000,29.930000,0.000000,0.000000,0.000000,49.050000,4.000000,1.000000,0.000000,17.000000,308.000000,3.000000,1505.550000,3.595581e+02,258.560327,15.450000,834.530000,42.596591,32.736068,0.000000,0.000000,0.000000,0.000000,1.000000,149.160000,1.000000,6.377825e+02,1.000191e+07,-0.677770,2015.000000
50%,476.740000,445.740000,389.910000,79.740000,0.000000,0.000000,13.130000,152.540000,11.000000,1.000000,1.000000,57.000000,918.000000,11.000000,6754.310000,7.248970e+02,569.077581,64.340000,1783.240000,68.444444,50.635354,0.000000,0.000000,1.000000,198.500000,2.000000,1117.680000,3.000000,2.426605e+03,1.000382e+07,-0.045714,2015.000000
75%,1087.670000,1036.700000,903.370000,184.840000,0.000000,0.000000,92.280000,396.061499,29.000000,1.000000,1.000000,119.000000,1759.000000,27.000000,21642.320000,1.095887e+03,981.093653,162.610000,3504.420000,113.831579,78.626119,1.000000,338.240000,2.000000,1514.560000,3.000000,3404.440000,7.000000,7.045423e+03,1.000576e+07,0.641711,2017.000000
max,22297.210000,21578.280000,18127.810000,4169.400000,181.060000,218.490000,4103.440000,7427.400583,423.000000,5.000000,1.000000,3199.000000,3506.000000,276.000000,247865.100000,1.000000e+09,6770.221342,6298.980000,267526.189924,3199.000000,2212.537118,11.000000,22297.210000,22.000000,30234.880000,37.000000,49746.970000,60.000000,1.000000e+09,1.000767e+07,4.151241,2024.000000

In [50]:
merged_data=merged_data.drop('random_noise', axis=1)

In [51]:
X = merged_data.drop(columns='repeat_purchase_90d')
y = merged_data['repeat_purchase_90d']

In [52]:
X_train, X_test, y_train, y_test = train_test_split(
X,
y, 
train_size=0.7,
stratify=y,
random_state=RANDOM_STATE,
)
len(X_train), len(X_test)

(4573, 1961)

In [53]:
tree_model = DecisionTreeClassifier(random_state=RANDOM_STATE)
tree_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [54]:
predictions_train=tree_model.predict(X_train)
predictions_test=tree_model.predict(X_test)
predictions_test[:10]

array([0, 1, 0, 1, 1, 1, 0, 1, 0, 1])

In [55]:
unt_train_acc = tree_model.score(X_train, y_train)
unt_test_acc = tree_model.score(X_test, y_test)
unt_train_f1 = f1_score(y_train, predictions_train)
unt_test_f1 = f1_score(y_test, predictions_test)

print(f'Default tree train: accuracy = {unt_train_acc:.3f} F1 = {unt_train_f1:.3f}')
print(f'Default tree test: accuracy = {unt_test_acc:.3f} F1 = {unt_test_f1:.3f}')

Default tree train: accuracy = 1.000 F1 = 1.000
Default tree test: accuracy = 0.620 F1 = 0.658